import { getAllArticles } from "../../lib/markdownParser";
import Head from "next/head";

import Post from "../../interfaces/article";
import Link from "next/link";
import type ArticleType from "../../interfaces/article";
import { List } from "../../components/article";

type Props = {
  articles: Post[];
};

const Projects = ({ articles }: Props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Projects</h1>
        <List
          route="/projects"
          articles={articles}
          emptyErrorMessage="아직 공개된 프로젝트가 없습니다."
        />
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const articles = await getAllArticles("_data/projects");

  return { props: { articles } };
};

export default Projects;
