import { getAllArticles } from "../../lib/markdownParser";
import Head from "next/head";

import Post from "../../interfaces/article";
import Link from "next/link";
import type ArticleType from "../../interfaces/article";

type Props = {
  articles: Post[];
};

const Projects = ({ articles }: Props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Projects</h1>
        {articles.length > 0 ? (
          <ul>
            {articles.map((article: ArticleType, index) => {
              return (
                <Link href={`/projects/${article.slug}`} passHref key={index}>
                  <li>
                    <h3>{article.frontmatter.title}</h3>
                    <p>{article.frontmatter.description}</p>
                    <p>{article.readingTime}</p>
                    <hr />
                  </li>
                </Link>
              );
            })}
          </ul>
        ) : (
          <p>아직 공개된 프로젝트가 존재하지 않습니다.</p>
        )}
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const articles = await getAllArticles("_data/projects");

  return { props: { articles } };
};

export default Projects;
