import { getAllArticles } from "../lib/markdownParser";
import Head from "next/head";
import Link from "next/link";

import Post from "../interfaces/article";
import type ArticleType from "../interfaces/article";
import { AuthorCard, List } from "../components/article";
import author from "../author";

type Props = {
  articles: Post[];
};

const Index = ({ articles }: Props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to {author.username}&#39;s page</h1>
        <AuthorCard />
        <List
          route="/blog"
          articles={articles}
          emptyErrorMessage="아직 공개된 글이 없습니다."
        />
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const articles = await getAllArticles("_data/blog");

  return { props: { articles } };
};

export default Index;
